name: publish

on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: pnpm run test:e2e
        env:
          VITE_MONGODB_URI: ${{ secrets.VITE_MONGODB_URI }}
          VITE_MONGODB_DATABASE: ${{ secrets.VITE_MONGODB_DATABASE }}
      - uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "release package"
          title: "Release package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
